### ISSUE TITLE
SyntaxError: await is only valid in async function

### ISSUE THREAD

**Issue by karl0ss** [balena-io-modules/drivelist#366]
Using your example on npmjs.org

```
const drivelist = require('drivelist');
 
const drives = await drivelist.list();
console.log(drives);
```

Gives me

```
const drives = await drivelist.list();
               ^^^^^

SyntaxError: await is only valid in async function
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```

```
$ node -v
v12.14.1
```

**Comment by karl0ss** [comment]
Only seems to work is i wrap in a async function 

```
const drivelist = require('drivelist');
 
async function test () {
const drives = await drivelist.list();
console.log(drives);
}

test()
```

**Comment by lurch** [comment]
Duplicate of #365 ?
