### ISSUE TITLE
[Feature] Electron 10/11 support

### ISSUE THREAD

**Issue by bennymeg** [balena-io-modules/drivelist#379]
Drivelist failed to recompile for Electron 10 / 11 using electron-compile (latest working version in Electron 9).

**Comment by leesc81** [comment]
Please support electron 11 too...
During electron-rebuild, the following error appears.

soochanglee@SooChancBookPro % ./node_modules/.bin/electron-rebuild
⠹ Building module: drivelist, Completed: 0gyp info find Python using Python version 3.8.2 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
⠸ Building module: drivelist, Completed: 0gyp http GET https://www.electronjs.org/headers/v11.0.3/node-v11.0.3-headers.tar.gz
⠴ Building module: drivelist, Completed: 0gyp http 503 https://www.electronjs.org/headers/v11.0.3/node-v11.0.3-headers.tar.gz
gyp WARN install got an error, rolling back install
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/soochanglee/MyApp/Application/VSCode/node_modules/drivelist'.
Error: 503 response downloading https://www.electronjs.org/headers/v11.0.3/node-v11.0.3-headers.tar.gz



Error: node-gyp failed to rebuild '/Users/soochanglee/MyApp/Application/VSCode/node_modules/drivelist'.
Error: 503 response downloading https://www.electronjs.org/headers/v11.0.3/node-v11.0.3-headers.tar.gz


    at ModuleRebuilder.rebuildNodeGypModule (/Users/soochanglee/MyApp/Application/VSCode/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at async Rebuilder.rebuildModuleAt (/Users/soochanglee/MyApp/Application/VSCode/node_modules/electron-rebuild/lib/src/rebuild.js:183:9)
    at async Rebuilder.rebuild (/Users/soochanglee/MyApp/Application/VSCode/node_modules/electron-rebuild/lib/src/rebuild.js:145:17)
    at async /Users/soochanglee/MyApp/Application/VSCode/node_modules/electron-rebuild/lib/src/cli.js:145:9

**Comment by shmulka** [comment]
Drivelist failed to recompile on Windows for Electron 10 / 11 using electron-rebuild.  Managed to rebuild only after reinstall of Window build tools 2017 (replacing 2015) `npm install --global windows-build-tools`. Although rebuild was successful and Drivelist now works within Electron 11, there are quite a few warnings displayed during the rebuild (MSB8029, MSB8012, C4996, C4309)

**Comment by bennymeg** [comment]
Maybe #392 PR will had solved this issue?

**Comment by jfbvm** [comment]
Any solution for this issue?
