### ISSUE TITLE
Electron app return error: Module did not self-register 

### ISSUE THREAD

**Issue by IvanOnishchenko** [balena-io-modules/drivelist#389]
When I call the library I get error: Module did not self-register: '.../node_modules/drivelist/build/Release/drivelist.node'.
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (.../node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (.../node_modules/drivelist/js/index.js:25:27)

**Comment by westonsoftware** [comment]
I'm getting the same "Module did not self-register" error when I call  drivelist.list() in my electron app.  
This runs fine when I run it locally with "start".
I'm using the electron-forge tool to "electron-forge make". 
I get the error when I run the published .exe file.
Do I need to copy any drivelist files into my out folder after I build or something?
Thanks
--Andy

**Comment by kimlimjustin** [comment]
Same here

**Comment by evsar3** [comment]
Same here too

**Comment by mesili** [comment]
I had the same problem and using `electron-rebuild` solved it right away:

1. Install `electron-rebuild`
2. run `cd ./node_modules/drivelist && ../.bin/electron-rebuild` 
3. Enjoy

**Comment by sziberov** [comment]
Same using NW.JS.

**Comment by thundron** [comment]
you have to rebuild the module for the specific nodejs+platform version, one way like @mesili mentioned is to use electron-rebuild
