### ISSUE TITLE
Error: Module did not self-register: 'drivelist.node'.

### ISSUE THREAD

**Issue by brgirgis** [balena-io-modules/drivelist#394]
I'm getting this error on both `Windows` and `Linux` when trying to start an electron app using the `Theia` IDE. I always make sure to rebuild using `npm rebuild` and that __DID NOT__ solve this issue. 

```
node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: Module did not self-register: '\\?\\node_modules\drivelist\build\Release\drivelist.node'.
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (node_modules\drivelist\js\index.js:25:27)
```

**Comment by brgirgis** [comment]
Not this package issue directly. Closing.

**Comment by navono** [comment]
@brgirgis Then how to resolve this error?

**Comment by seb-mtl** [comment]
Not the scope of this repo. You may have compiled `drivelist` with your local node installation. Electron and node have both a different ABI. You might want to look for `postinstall` and build the module through Electron.

**Comment by rlwoodjr** [comment]
> 

How would a person un-complie drive list?

**Comment by lurch** [comment]
You don't need to un-compile, the source code is available? https://github.com/balena-io-modules/drivelist/tree/master/src

**Comment by rlwoodjr** [comment]
> Error: Module did not self-register: '\\?\\node_modules\drivelist\build\Release\drivelist.node'.

I am trying to fix the 
Error: Module did not self-register: '\\?\\node_modules\drivelist\build\Release\drivelist.node'.

It is an electron app.

**Comment by lurch** [comment]
I don't work on this project myself (I'm just a helpful community member), but does https://github.com/balena-io-modules/drivelist/issues/389#issuecomment-850784173 help?

**Comment by rlwoodjr** [comment]
Thanks!
